# Dockerfile for the client application
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY client/package.json ./

RUN npm install

# Bundle app source
COPY client/ .

# Build the React application
RUN npm run build

# Install serve to serve the production build
RUN npm install -g serve

# The port that serve will use to serve the application
EXPOSE 5000

CMD ["serve", "-s", "build", "-l", "5000"]